// Generated by Wrangler by running `wrangler types`

interface Env {
	routes: [{"pattern":"survey.rethink.buleegasy.space/api/*","zone_name":"buleegasy.space"},{"pattern":"rethink.buleegasy.space/api/*","zone_name":"buleegasy.space"}];
	API_KEY: string;
	API_BASE_URL: string;
	MODEL_NAME: string;
	FIREBASE_API_KEY: string;
	FIREBASE_PROJECT_ID: string;
	TURNSTILE_SECRET_KEY: string;
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
